pipeline
{
  agent any
  stages{
    
    stage('gitpullstage'){
    steps{      
            git branch: 'branch-team', credentialsId: 'sreenivas', url: 'https://github.com/ravulasrinivas/company-name.git'
          }
    
    }
    stage('buildeploy'){
    steps{   
          sh "./deploy.sh"
           }
     }
    
  } 
  
}

